# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='\u59d3\u540d')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='\u8054\u7cfb\u7535\u8bdd')),
                ('qq', models.CharField(blank=True, max_length=50, verbose_name='QQ')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='\u8054\u7cfb\u5730\u5740')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='\u516c\u53f8')),
                ('description', models.TextField(verbose_name='\u4e2a\u4eba\u7b80\u4ecb')),
                ('image', models.ImageField(blank=True, upload_to='photo/', verbose_name='\u4e2a\u4eba\u7167\u7247')),
            ],
        ),
        migrations.CreateModel(
            name='LawyerTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
