# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeRegulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description_file', models.FileField(blank=True, upload_to='file/', verbose_name='\u63cf\u8ff0\u6587\u4ef6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JudicialInterpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description_file', models.FileField(blank=True, upload_to='file/', verbose_name='\u63cf\u8ff0\u6587\u4ef6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawsAndRegulations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description_file', models.FileField(blank=True, upload_to='file/', verbose_name='\u63cf\u8ff0\u6587\u4ef6')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OtherProvisions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('description_file', models.FileField(blank=True, upload_to='file/', verbose_name='\u63cf\u8ff0\u6587\u4ef6')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
