# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_administrativeregulations_judicialinterpretation_lawsandregulations_otherprovisions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LawsAndRegulations',
            new_name='LegalProvisions',
        ),
    ]
