# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170628_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.CharField(blank=True, max_length=50)),
                ('content', models.CharField(blank=True, max_length=500)),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('has_reply', models.BooleanField(default=False)),
            ],
        ),
    ]
