# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.CharField(blank=True, max_length=2000)),
                ('submit_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
