# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_communicate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicate',
            name='content',
            field=models.TextField(),
        ),
    ]
