# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20170701_2240'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
                ('submit_time', models.DateTimeField(auto_now=True)),
                ('news_type', models.CharField(choices=[('\u884c\u4e1a\u52a8\u6001', '\u884c\u4e1a\u52a8\u6001'), ('\u6cd5\u6cbb\u793e\u4f1a', '\u6cd5\u6cbb\u793e\u4f1a'), ('\u6cd5\u5f8b\u524d\u6cbf', '\u6cd5\u5f8b\u524d\u6cbf')], max_length=10, verbose_name='\u65b0\u95fb\u7c7b\u578b')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='communications',
            name='communications_type',
            field=models.CharField(choices=[('\u4e1a\u52a1\u4ea4\u6d41', '\u4e1a\u52a1\u4ea4\u6d41'), ('\u6d3b\u52a8\u4ea4\u6d41', '\u6d3b\u52a8\u4ea4\u6d41')], max_length=10, verbose_name='\u4ea4\u6d41\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='communications',
            name='content',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='communications',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
