# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20170701_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyerteam',
            name='description',
            field=models.TextField(blank=True, verbose_name='\u56e2\u961f\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='lawyerteam',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='\u56e2\u961f\u540d\u79f0'),
        ),
    ]
