# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20170702_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u7c7b\u578b')),
                ('description', models.TextField(blank=True, verbose_name='\u670d\u52a1\u4ecb\u7ecd')),
            ],
        ),
    ]
