# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_lawservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawservice',
            name='service_type',
            field=models.CharField(choices=[('\u8bc9\u8bbc\u4e1a\u52a1', '\u8bc9\u8bbc\u4e1a\u52a1'), ('\u975e\u8bc9\u4e1a\u52a1', '\u975e\u8bc9\u4e1a\u52a1'), ('\u59d4\u6258\u6d41\u7a0b', '\u59d4\u6258\u6d41\u7a0b')], max_length=20, verbose_name='\u670d\u52a1\u7c7b\u578b'),
        ),
    ]
