# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20170702_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativeregulations',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='judicialinterpretation',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lawyerteam',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u56e2\u961f\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='legalprovisions',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='otherprovisions',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
