# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20170702_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LawyerCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='\u6807\u9898')),
                ('content', models.TextField(verbose_name='\u5185\u5bb9')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
